name: DailyBuild

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  auto-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build latest
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          event-type: Build Latest
          client-payload: '{ "node": 18, "tag": "latest", "repo": "${{ github.repository }}" }'

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 3
